bootstrap.servers=broker:29092

group.id=kafka-connect-ais

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

offset.storage.topic=_connect-offsets
offset.storage.replication.factor=1
config.storage.topic=_connect-configs
config.storage.replication.factor=1
status.storage.topic=_connect-status
status.storage.replication.factor=1

plugin.path=/opt/kafka/plugins

rest.advertised.host.name=kafka-connect
